# name of the workflow
name: Nasa Project CI

# control when the workflow will run using "on" preperty
on:
# it will run on push request 
  push:
    branches: [main]
    # it will run on pull request
      pull_request: 
        branches: [main]
# jobs need to run when one of the above two event is triggered
jobs:
  build: 
  # specifying the operating system on which the build will run
    runs-on:  windows-latest
      # steps for the build job
        steps: 
          -uses: actions/checkout@v2
          -name: Use node.js version16
          -uses: actions/setup-node@v2
            with: 
              node-version: '16'
          # to run our own command 
          -run: npm install
          -run: npm run build --prefix client